environment:
  database:
    type: POSTGRESQL
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 99000
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: "omega-complex-secret"
    expiration: 7000

